runtime: python39

instance_class: F2

entrypoint: gunicorn -b :$PORT my_web_project.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "my_web_project.settings"
  APPENGINE_URL: "https://barrackouma.wn.r.appspot.com/"  # Replace PROJECT_ID with your actual Google Cloud project ID

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
